### ISSUE TITLE
traitlets.traitlets.TraitError: Traitlet does not exist: r1_product

### ISSUE THREAD

**Issue by jonpsy** [cta-observatory/dl1-data-handler#81]
Hey there, 
In the process of setting up the environment, I faced a hard time to get the necessary dataset to run the software. I used 
**gamma_test.simtel.gz** : https://github.com/cta-observatory/ctapipe-extra/blob/master/ctapipe_resources/gamma_test.simtel.gz

I created a folder named **inputs** in installation directory, and **outputs** directory and configured my _runlist accordingly.  I got the above-mentioned error.

![Screenshot from 2020-02-04 23-07-50](https://user-images.githubusercontent.com/45007169/73771942-4ae63c00-47a5-11ea-9b63-8bede2bee868.png)
![Screenshot from 2020-02-04 23-08-14](https://user-images.githubusercontent.com/45007169/73772119-9a2c6c80-47a5-11ea-8285-26a989dc62b6.png)

**Comment by TjarkMiener** [comment]
Hi @NanuSai. Could you please post your config file and the ctapipe version you installed? 

I wasn't aware of the simtel files in ctapipe-extra. Does `gamma_test.simtel.gz` contains a handful of gamma events so that outsiders would be able to test CTA software, @MaxNoe?

**Comment by MaxNoe** [comment]
It's a small by truncation, very old file. I think from PROD2.

**Comment by MaxNoe** [comment]
But I think the problem here is a new ctapipe version with a version of the data handler that do not work together. The camera calibrator API has changed. Pinging @watsonjj

**Comment by vuillaut** [comment]
I agree with @MaxNoe, I think the installed version of ctapipe is not the right one here.

**Comment by TjarkMiener** [comment]
Yes, that's right. For data handler v0.7.3 you need to install ctapipe v0.6.2, @NanuSai. 

I will finish PR #78 this week, so we could make a new data-handler release, solving all the installation issues. (However, the current data-handler master is working fine with the latest ctapipe version)

**Comment by NanuSai** [comment]
@TjarkMiener  , as for the version of ctapipe, I'm using 
**ctapipe** : 0.7.0
 **ctapipe-extra**  : 0.2.18

![rsz_screenshot_from_2020-02-05_19-23-29](https://user-images.githubusercontent.com/45007169/73848039-5ab95b00-484d-11ea-80d4-5197614b9077.png)

I installed ctapipe v0.6.2, and now I'm facing the following error.  

![Screenshot from 2020-02-05 19-31-51](https://user-images.githubusercontent.com/45007169/73848475-34e08600-484e-11ea-97c1-f0c3c4954c87.png)

I think the problem is with the dataset? Am I using the wrong dataset since I couldn't find any specific link to download simtel file in this repo. 

I'm kinda newbie to open-source so maybe I made a mistake on understanding the README.md

**Comment by TjarkMiener** [comment]
Hi @NanuSai. Let me inspect that simtel file and try to run the data handler with it. We can discuss offline (tmiener@ucm.es), if you want.

**Comment by MaxNoe** [comment]
I think the problem here is again not with the simtel file but with the ctapipe/dl1 handler version.

`image.shape[0] == 2` looks like dl1 data handler is expecting multiple gain channels here. 

I don't exactly know when this change was made in ctapipe, to ensure only one gain is used in image.

**Comment by MaxNoe** [comment]
@NanuSai, just a copy of the error would be easier to read than this large screenshots.

Just copy the text and put it inside ` ``` `

**Comment by MaxNoe** [comment]
can you post the output of `conda list`?

**Comment by NanuSai** [comment]
> can you post the output of `conda list`?
```
# packages in environment at /home/psykik/anaconda3/envs/dl1:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0    anaconda
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py37_1  
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-project          0.8.3                      py_0    conda-forge
argh                      0.26.2                py37_1001    conda-forge
asn1crypto                1.3.0                    py37_0    conda-forge
astroid                   2.3.3                    py37_1    conda-forge
astropy                   3.2.3            py37h516909a_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
autopep8                  1.5                        py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.os              0.1.1                 py37_1001    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.8.2                    py37_0    conda-forge
bitarray                  1.2.1            py37h516909a_0    conda-forge
bkcharts                  0.2                      py37_0    anaconda
blas                      2.14                   openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.17.1               he1b5a44_0    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.1            py37hc1659b7_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
corsikaio                 0.2.0              pyh1d22016_0    cta-observatory
cryptography              2.8              py37h72c5cf5_1    conda-forge
ctapipe                   0.6.2            py37ha8d69ae_2    cta-observatory
ctapipe-extra             0.2.18                        0    cta-observatory
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.14          py37he1b5a44_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.10.1                     py_0    conda-forge
dask-core                 2.10.1                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20181111                   py_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
dl1_data_handler          0.7.4                    py37_0    bryankim96
docutils                  0.16                     py37_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
eventio                   0.11.0           py37h39e3cac_0    cta-observatory
expat                     2.2.9                he1b5a44_2    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
filelock                  3.0.10                     py_0    conda-forge
flake8                    3.7.9                    py37_0    conda-forge
flask                     1.1.1                      py_1    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
future                    0.18.2                   py37_0    conda-forge
get_terminal_size         1.0.0                haa9412d_0    anaconda
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gevent                    1.4.0            py37h516909a_0    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.0                he1b5a44_1    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
graphviz                  2.38.0            hf68f40c_1011    conda-forge
greenlet                  0.4.15           py37h516909a_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_1    conda-forge
gstreamer                 1.14.5               h36ae1b5_1    conda-forge
h5py                      2.10.0          nompi_py37h513d04c_101    conda-forge
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
hypothesis                5.4.1                      py_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
iminuit                   1.3.8            py37hb3f55d8_0    conda-forge
importlib_metadata        1.5.0                    py37_0    conda-forge
inflect                   4.1.0                    py37_0    conda-forge
intel-openmp              2019.5                      281    anaconda
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.12.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isort                     4.3.21                   py37_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jaraco.itertools          5.0.0                      py_0    conda-forge
jbig                      2.1               h14c3975_2001    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.14.1                   py37_0    conda-forge
jeepney                   0.4.2                      py_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
keyring                   21.1.0                   py37_0    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.4               h173b8e3_0    anaconda
lazy-object-proxy         1.4.3            py37h516909a_1    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libarchive                3.3.3             hb44662c_1005    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
liblapacke                3.8.0               14_openblas    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_1    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                hea5a465_1    anaconda
libxslt                   1.1.33               h7d1a2b0_0    anaconda
llvmlite                  0.31.0           py37h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.4.2            py37hefd8a0e_0    anaconda
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.2                    py37_1    anaconda
matplotlib-base           3.1.2            py37hef1b27d_1    anaconda
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
mkl                       2019.5                      281    anaconda
mkl-service               2.3.0            py37h516909a_0    conda-forge
mkl_fft                   1.1.0            py37hc1659b7_1    conda-forge
mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
mock                      3.0.5                    py37_0    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
mpc                       1.1.0             h04dde30_1006    conda-forge
mpfr                      4.0.2                he80fd80_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1                  he6710b0_1  
networkx                  2.4                        py_0    conda-forge
nltk                      3.4.4                      py_0    conda-forge
nose                      1.3.7                 py37_1003    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
numba                     0.48.0           py37hb3f55d8_0    conda-forge
numexpr                   2.7.1            py37hb3f55d8_0    conda-forge
numpy                     1.18.1           py37h95a1406_0    conda-forge
numpy-base                1.18.1           py37h2f8d375_1    anaconda
numpydoc                  0.9.2                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openpyxl                  3.0.3                      py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.0            py37hb3f55d8_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           he7ab937_1005    conda-forge
parso                     0.6.1                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
path                      13.1.0                   py37_0    conda-forge
path.py                   12.4.0                        0    conda-forge
pathlib2                  2.3.5                    py37_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.0            py37h34e0f95_0    anaconda
pip                       20.0.2                   py37_1    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
psutil                    5.6.7            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3           py37h516909a_1002    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycrypto                  2.6.1           py37h516909a_1003    conda-forge
pycurl                    7.43.0.5         py37h16ce93b_0    conda-forge
pydocstyle                5.0.2                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyhessio                  2.1.1            py37h39e3cac_1    cta-observatory
pylint                    2.4.4                    py37_0    conda-forge
pyodbc                    4.0.28           py37he1b5a44_0    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.9.2            py37h22d08a2_1    anaconda
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pytables                  3.6.1            py37h9f153d1_1    conda-forge
pytest                    5.3.5                    py37_0    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.7.0                      py_0    conda-forge
pytest-astropy-header     0.1.2                      py_0    conda-forge
pytest-doctestplus        0.4.0                      py_0    conda-forge
pytest-openfiles          0.4.0                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
pytest-runner             5.2                        py_0    conda-forge
python                    3.7.6                h0371630_2    anaconda
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.3.4                      py_0    conda-forge
python-language-server    0.31.7                   py37_0    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyxdg                     0.26                       py_0    conda-forge
pyyaml                    5.3              py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qdarkstyle                2.8                        py_0    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
qtawesome                 0.6.1                      py_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_1    conda-forge
rope                      0.16.0                     py_0    conda-forge
rtree                     0.9.3            py37h7b0cdae_0    conda-forge
ruamel_yaml               0.15.80         py37h516909a_1000    conda-forge
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scikit-learn              0.22.1           py37hcdab131_1    conda-forge
scipy                     1.4.1            py37h921218d_0    conda-forge
seaborn                   0.10.0                     py_1    conda-forge
secretstorage             3.1.2                    py37_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.1.0                   py37_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py37_1000    conda-forge
sip                       4.19.20          py37he1b5a44_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
snappy                    1.1.8                he1b5a44_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcollections         1.1.2                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sphinx                    2.3.1                      py_0    conda-forge
sphinxcontrib             1.0                      py37_1    anaconda
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
spyder                    4.0.1                    py37_0    conda-forge
spyder-kernels            1.8.1                    py37_1    conda-forge
sqlalchemy                1.3.13           py37h516909a_0    conda-forge
sqlite                    3.30.1               h7b6447c_0  
statsmodels               0.11.0           py37h516909a_0    conda-forge
sympy                     1.5.1                    py37_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.42.1                     py_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
typed-ast                 1.4.1            py37h516909a_0    conda-forge
ujson                     1.35            py37h516909a_1001    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unixodbc                  2.3.7             h227dcee_1000    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
watchdog                  0.10.1                   py37_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.1                     py_0    conda-forge
wheel                     0.34.2                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
wrapt                     1.11.2           py37h516909a_0    conda-forge
wurlitzer                 2.0.0                    py37_0    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.2.7                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.2.2                h516909a_1    conda-forge
yapf                      0.28.0                     py_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      2.1.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.0                h3b9ef0a_0    conda-forge



```


To make life easy, here are the dependencies list and their version required for this repo
```
pytables-3.6.1           
numpy-1.18.1           
numpy-base-1.18.1           
numpydoc-0.9.2                      
ctapipe-0.6.2           
ctapipe-extra- 0.2.18                        
pyhessio- 2.1.1           
dl1_data_handler-0.7.4
```

**Comment by MaxNoe** [comment]
Any reason, why you are not using the latest data handler (0.8.0 or 0.8.1)?

**Comment by TjarkMiener** [comment]
@MaxNoe Sure, the installation of ctapipe/data handler is causing the problem and not the simtel file. I just wanted to give @NanuSai a hand with the installation of the packages and therefore I wanted to produce a DL1 h5 file with the gamma_test simtel file by myself first (before giving advice). I did produce the h5 file following the installation instruction in the current dl1-data-handler master branch, except I checkout to commit 'f350a04' (PR from @watsonjj which solved the arrival time issue). The current master of ctapipe is not compatible with the dl1-data handler. I will have a look tomorrow.

**Comment by NanuSai** [comment]
@TjarkMiener,
Okay I've done as you told and then ran the following command

`python scripts/generate_runlist.py  --num_inputs_per_run 1`
Which made runlist.yml, when I checked its contents, I found this
``` [] ```
Then I ran,
python scripts/write_data.py runlist.yml 
Which downloaded something, which however didn't generate any output , so I used my own runlist taking `example_runlist.yml` as reference, named it `my_runlist.yml` . It's contents
```-inputs:
        - './inputs/gamma_test.simtel.gz'

-target: './outputs/output_file_1.h5'
```
Using this as my runlist, I ran the following command 
`python scripts/write_data.py my_runlist.yml `

Which threw the following error:
```
Traceback (most recent call last):
  File "scripts/write_data.py", line 52, in <module>
    len([input_file for run in runlist for input_file in run['inputs']])))
  File "scripts/write_data.py", line 52, in <listcomp>
    len([input_file for run in runlist for input_file in run['inputs']])))
TypeError: string indices must be integers
```.
